<?xml version="1.0"?>
<package format="2">
  <name>theta_s_ros</name>
  <version>0.0.0</version>
  <description>The theta_s_ros package</description>

  <maintainer email="amsl@todo.todo">amsl</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>image_geometry</depend>
  <depend>pluginlib</depend>
  <depend>nodelet</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
